services:
# -------------------- Web App -------------------
  webapp:
    image: python:3.12-slim
    container_name: lesson5_python_webapp
    working_dir: /app
    ports:
      - "8080:8080"
    entrypoint: ["sh", "entrypoint.sh"]
    healthcheck:
      test: ["CMD-SHELL", "test -f /app/app-ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      APP_MESSAGE: "Welcome to the Course App"
      APP_STORE: redis
      APP_REDIS_URL: redis://redis:6379/0
# ------------------- Redis Service --------------
  redis:
    image: redis:7
    container_name: lesson5_redis_service
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - redis_data:/data

volumes:
  redis_data:

