FROM apache/spark:latest

USER root

# Системні залежності
RUN apt-get update && apt-get install -y \
    wget curl \
    && rm -rf /var/lib/apt/lists/*

# ─── Завантажити JAR-и для Kafka + S3A (MinIO) ───────────────────
ENV SPARK_JARS_DIR=/opt/bitnami/spark/jars

RUN wget -q -P ${SPARK_JARS_DIR} \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar && \
    wget -q -P ${SPARK_JARS_DIR} \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.0/kafka-clients-3.4.0.jar && \
    wget -q -P ${SPARK_JARS_DIR} \
    https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar && \
    wget -q -P ${SPARK_JARS_DIR} \
    https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar && \
    wget -q -P ${SPARK_JARS_DIR} \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    wget -q -P ${SPARK_JARS_DIR} \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY kafka_to_minio.py .

CMD ["spark-submit", \
     "--master", "local[2]", \
     "/app/kafka_to_minio.py"]
