{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "data-pipeline.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-pipeline.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: {{ .Values.minio.service.consolePort }}
{{- end }}
