{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    {{- include "data-pipeline.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
  ports:
    - name: api
      port: {{ .Values.minio.service.port }}
      targetPort: api
    - name: console
      port: {{ .Values.minio.service.consolePort }}
      targetPort: console
{{- end }}
